### ISSUE TITLE
无法管理评论

### ISSUE THREAD

**Issue by ghost** [mx-space/core#1232]
### Describe the bug

如题 管理面板无法管理评论
![image](https://github.com/mx-space/core/assets/68452494/d1ca23fb-4a6e-4b11-a25a-b6c4fd05c7fc)
后端日志如下
```
mx-server  | 10:49:02  ERROR   [Catch]  Schema hasn't been registered for model "Post".
mx-server  | Use mongoose.model(name, schema)
mx-server  | 
mx-server  |   Use mongoose.model(name, schema)
mx-server  |   at NativeConnection.Connection.model (index.js:200:4337)
mx-server  |   at _getModelFromConn (index.js:555:1606)
mx-server  |   at addModelNamesToMap (index.js:555:344)
mx-server  |   at getModelsMapForPopulate (index.js:549:12088)
mx-server  |   at populate (index.js:669:601)
mx-server  |   at _populate (index.js:666:8356)
mx-server  |   at index.js:666:8179
mx-server  |   at new Promise (<anonymous>)
mx-server  |   at Function.populate (index.js:666:8156)
mx-server  |   at oe.Query._find (index.js:742:1047)
mx-server  |   at runMicrotasks (<anonymous>)
mx-server  |   at processTicksAndRejections (node:internal/process/task_queues:96:5)
mx-server  |   at async oe.Query.exec (index.js:758:5133)
mx-server  |   at async Promise.all (index 1)
mx-server  |   at async CommentService.getComments (index.js:2:157811)
mx-server  |   at async CommentController.getRecentlyComments (index.js:2:135455)

```

### Reproduction

在管理面板中点击评论选项卡

### System Info

```Shell
System:
    OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (1) x64 DO-Premium-Intel
    Memory: 977.62 MB / 1.92 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 20.5.1 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 9.8.0 - /usr/bin/npm
    pnpm: 8.7.4 - ~/.local/share/pnpm/pnpm
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Innei** [comment]
感谢反馈
