### ISSUE TITLE
更新后无法查看评论了

### ISSUE THREAD

**Issue by laogou717** [mx-space/core#1478]
## 上次更新是年前，今天上班的时候看了一下后台发现看不了评论了，然后我更新了一下。还是像图片中显示的这样，其他功能正常。
 使用 **docker** 部署

![image](https://github.com/mx-space/core/assets/128354383/526aeee1-736d-4d99-b450-00a491b96c4e)
![image](https://github.com/mx-space/core/assets/128354383/51abe3d4-6fc3-46d0-8579-0b5a25b1a278)
![image](https://github.com/mx-space/core/assets/128354383/b9c876b2-499f-4d1c-a177-81936d27fde5)

### Reproduction

无

### System Info

```Shell
错误日志
17:56:28  ERROR   [AuthService]  clerk jwt valid error: invalid algorithm
17:56:28  ERROR   [AuthService]  clerk jwt valid error: invalid algorithm
17:56:28  WARN   [AllExceptionsFilter]  IP: 43.207.68.61 错误信息：(401) 身份过期 Path: /api/v2/aggregate/stat?t=1708509376108
17:56:28  ERROR   [AuthService]  clerk jwt valid error: invalid algorithm
17:56:28  WARN   [AllExceptionsFilter]  IP: 43.207.68.61 错误信息：(404) Cannot GET /api/v2/init?t=1708509376285 Path: /api/v2/init?t=1708509376285
17:56:33  ERROR   [AuthService]  clerk jwt valid error: invalid algorithm
17:56:33  WARN   [UserService]  主人已登录，IP: 43.207.68.61
17:56:35  ERROR   [Catch]  Schema hasn't been registered for model "recentlies".
Use mongoose.model(name, schema)

  Use mongoose.model(name, schema)
  at Connection.model (entrypoints.js:241:4323)
  at _getModelFromConn (entrypoints.js:596:1564)
  at addModelNamesToMap (entrypoints.js:596:345)
  at getModelsMapForPopulate (entrypoints.js:590:11812)
  at populate (entrypoints.js:710:581)
  at _populate (entrypoints.js:707:7939)
  at entrypoints.js:707:7780
  at new Promise (<anonymous>)
  at Function.populate (entrypoints.js:707:7757)
  at le.Query._find (entrypoints.js:783:1016)
[February 21, 2024 at 5:56:35 PM] /api/v2/comments?t=1708509382922&page=1&size=10&state=0: Schema hasn't been registered for model "recentlies".
Use mongoose.model(name, schema)
MissingSchemaError: Schema hasn't been registered for model "recentlies".
Use mongoose.model(name, schema)
    at Connection.model (/app/entrypoints.js:241:4323)
    at _getModelFromConn (/app/entrypoints.js:596:1564)
    at addModelNamesToMap (/app/entrypoints.js:596:345)
    at getModelsMapForPopulate (/app/entrypoints.js:590:11812)
    at populate (/app/entrypoints.js:710:581)
    at _populate (/app/entrypoints.js:707:7939)
    at /app/entrypoints.js:707:7780
    at new Promise (<anonymous>)
    at Function.populate (/app/entrypoints.js:707:7757)
    at le.Query._find (/app/entrypoints.js:783:1016)
17:56:41  ERROR   [Catch]  Schema hasn't been registered for model "recentlies".
Use mongoose.model(name, schema)

  Use mongoose.model(name, schema)
  at Connection.model (entrypoints.js:241:4323)
  at _getModelFromConn (entrypoints.js:596:1564)
  at addModelNamesToMap (entrypoints.js:596:345)
  at getModelsMapForPopulate (entrypoints.js:590:11812)
  at populate (entrypoints.js:710:581)
  at _populate (entrypoints.js:707:7939)
  at entrypoints.js:707:7780
  at new Promise (<anonymous>)
  at Function.populate (entrypoints.js:707:7757)
  at le.Query._find (entrypoints.js:783:1016)
[February 21, 2024 at 5:56:41 PM] /api/v2/comments?t=1708509388704&page=1&size=10&state=0: Schema hasn't been registered for model "recentlies".
Use mongoose.model(name, schema)
MissingSchemaError: Schema hasn't been registered for model "recentlies".
Use mongoose.model(name, schema)
    at Connection.model (/app/entrypoints.js:241:4323)
    at _getModelFromConn (/app/entrypoints.js:596:1564)
    at addModelNamesToMap (/app/entrypoints.js:596:345)
    at getModelsMapForPopulate (/app/entrypoints.js:590:11812)
    at populate (/app/entrypoints.js:710:581)
    at _populate (/app/entrypoints.js:707:7939)
    at /app/entrypoints.js:707:7780
    at new Promise (<anonymous>)
    at Function.populate (/app/entrypoints.js:707:7757)
    at le.Query._find (/app/entrypoints.js:783:1016)
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by laogou717** [comment]
之前已读的评论和垃圾评论可以正常查看

**Comment by Innei** [comment]
感谢反馈
