### ISSUE TITLE
Marked 错误 Maximum call stack size exceeded

### ISSUE THREAD

**Issue by miaoermua** [mx-space/core#1922]
### Describe the bug

```log
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192) 


 ERROR   [Catch]  Maximum call stack size exceeded
Please report this to https://github.com/markedjs/marked.

  Please report this to https://github.com/markedjs/marked.
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  [90mat _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192) 


 ERROR   [Catch]  Maximum call stack size exceeded
Please report this to https://github.com/markedjs/marked.

  Please report this to https://github.com/markedjs/marked.
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192) 


 ERROR   [Catch]  Maximum call stack size exceeded
Please report this to https://github.com/markedjs/marked.

  Please report this to https://github.com/markedjs/marked.
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192)
  at _Renderer.<anonymous> (/app/entrypoints.js:1905:347192) 
```
<img width="681" alt="E6297B7BE87D586EE7A4482EE982736F" src="https://github.com/user-attachments/assets/5ca0c529-f925-469f-bf82-15e74d503113">

### Reproduction

have not

### System Info

```Shell
{"name":"@mx-space/core","author":"Innei <https://innei.in>","version":"6.0.1","homepage":"https://github.com/mx-space/core/tree/master/apps/core#readme","issues":"https://github.com/mx-space/core/issues"}


发行版本 debian
内核版本 4.19.0-17-amd64
系统类型 x86_64
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by miaoermua** [comment]
https://github.com/markedjs/marked/pull/3380

**Comment by Innei** [comment]
Maybe fixed? @miaoermua
