### ISSUE TITLE
解密错误 bad decrypt

### ISSUE THREAD

**Issue by miaoermua** [mx-space/core#2096]
### Describe the bug

[mx-server-20240906024116.log](https://github.com/user-attachments/files/16898912/mx-server-20240906024116.log)
[mx-server-20240906022642.log](https://github.com/user-attachments/files/16898914/mx-server-20240906022642.log)

```json
{
  "ok": 0,
  "message": "error:1C800064:Provider routines::bad decrypt"
}
```

给应该是 v6.x 的升级到最新 latest 出现了，解密错误

### Reproduction

have not

### System Info

```Shell
mx_core: v7.x


version: '3.8'

services:
  app-kami:
    container_name: mx-kami
    image: miaoer/my-kami:latest
    environment:
      - NODE_ENV=production 
      - BASE_URL=https://api.miaoer.xyz
      - NEXT_PUBLIC_API_URL=https://api.miaoer.xyz/api/v2
      - NEXT_PUBLIC_GATEWAY_URL=https://api.miaoer.xyz
    ports:
      - '2323:2323'
    command: 'npx next start -p 2323'
    user: node
    networks:
      - app-network
    restart: always

  app-server:
    container_name: mx-server
    image: innei/mx-server:latest
    command: node index.js --redis_host=redis --db_host=mongo --allowed_origins=${ALLOWED_ORIGINS} --jwt_secret=${JWT_SECRET} --encrypt_key=${SOC} --encrypt_enable --color
    environment:
      - TZ=Asia/Shanghai
      - NODE_ENV=production
      - CBOR_NATIVE_ACCELERATION_DISABLED=true
    volumes:
      - ./data/mx-space:/root/.mx-space
    ports:
      - '127.0.0.1:2333:2333'
    depends_on:
      - mongo
      - redis
    links:
      - mongo
      - redis
    networks:
      - app-network
    restart: on-failure:16
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://127.0.0.1:2333/api/v2/ping']
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  mongo:
    container_name: mongo
    image: mongo:6.0.7
    volumes:
      - ./data/db:/data/db
    networks:
      - app-network
    restart: always
  redis:
    image: redis
    container_name: redis

    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by miaoermua** [comment]
```logs
Starting Mix Space
============== Configurations ==============
Listen Port: 2333
MongoDB: mongodb://mongo:27017/mx-space
Redis: redis:6379
Allowed Origins: miaoer.xyz,www.miaoer.xyz,v6.www.miaoer.xyz,cdn.miaoer.xyz
Config Path: NULL
Encryption: true
Cluster: false
============================================
[Nest] 1  - 09/06/2024, 3:14:41 AM     LOG 数据目录已经建好：/root/.mx-space
[Nest] 1  - 09/06/2024, 3:14:41 AM     LOG 临时目录已经建好：/tmp/mx-space
[Nest] 1  - 09/06/2024, 3:14:41 AM     LOG 日志目录已经建好：/root/.mx-space/log
[Nest] 1  - 09/06/2024, 3:14:41 AM     LOG 资源目录已经建好：/root/.mx-space/assets
[Nest] 1  - 09/06/2024, 3:14:41 AM     LOG 文件存放目录已经建好：/root/.mx-space/static
[Nest] 1  - 09/06/2024, 3:14:41 AM     LOG 文件回收站目录已经建好：/tmp/mx-space/trash
cwd:  /app

 WARN  Encrypt is enabled, please remember encrypt key. Your key is starts with 168

ℹ ENV: production
✔ [P1] Server listen on: http://127.0.0.1:2333
✔ [P1] Admin Local Dashboard: http://127.0.0.1:2333/proxy/qaqdmin
ℹ [P1] If you want to debug local dev dashboard on production environment with https domain, you can go to: https://<your-prod-domain>/proxy/qaqdmin/dev-proxy
ℹ Server is up. +4841ms

 ERROR   [ConfigsService]  获取配置失败 


 ERROR  unhandledRejection: error:1C800064:Provider routines::bad decrypt

  at Decipheriv.final (node:internal/crypto/cipher:193:29)
  at EncryptUtil.decrypt (entrypoints.js:2:612567)
  at decryptProperty (entrypoints.js:2:244136)
  at decryptObject (entrypoints.js:2:244423)
  at decryptObject (entrypoints.js:2:244380)
  at ConfigsService.getConfig (entrypoints.js:2:253545)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async ConfigsService.getConfig (entrypoints.js:2:253600)
  at async ConfigsService.getConfig (entrypoints.js:2:253600)
  at async ConfigsService.getConfig (entrypoints.js:2:253600)


 ERROR   [ConfigsService]  获取配置失败 


 ERROR   [Catch]  error:1C800064:Provider routines::bad decrypt

  at Decipheriv.final (node:internal/crypto/cipher:193:29)
  at EncryptUtil.decrypt (entrypoints.js:2:612567)
  at decryptProperty (entrypoints.js:2:244136)
  at decryptObject (entrypoints.js:2:244423)
  at decryptObject (entrypoints.js:2:244380)
  at ConfigsService.getConfig (entrypoints.js:2:253545)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async ConfigsService.getConfig (entrypoints.js:2:253600)
  at async ConfigsService.getConfig (entrypoints.js:2:253600)
  at async ConfigsService.getConfig (entrypoints.js:2:253600) 


 ERROR   [ConfigsService]  获取配置失败 


 ERROR   [Catch]  error:1C800064:Provider routines::bad decrypt

  at Decipheriv.final (node:internal/crypto/cipher:193:29)
  at EncryptUtil.decrypt (entrypoints.js:2:612567)
  at decryptProperty (entrypoints.js:2:244136)
  at decryptObject (entrypoints.js:2:244423)
  at decryptObject (entrypoints.js:2:244380)
  at ConfigsService.getConfig (entrypoints.js:2:253545)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async ConfigsService.getConfig (entrypoints.js:2:253600)
  at async ConfigsService.getConfig (entrypoints.js:2:253600)
  at async ConfigsService.getConfig (entrypoints.js:2:253600) 
```

**Comment by miaoermua** [comment]
`--encrypt_key=${SOC} --encrypt_enable` 删掉好像就可以了，现在回滚到老版本了😹
