### ISSUE TITLE
Algolia搜索分页

### ISSUE THREAD

**Issue by Do1e** [mx-space/core#2243]
### Clear and concise description of the problem

免费的Algolia有10KB大小的限制，然而文章长度会偶尔超出。

### Suggested solution

一个可行的解决方案是将文章分片上传。Algolia索引是根据`objectID`，因此我将这个改了，并进行分片

Python分片示例：

```python
url = "http://127.0.0.1:2333/api/v2/search/algolia/import-json"
headers = {
    "Authorization": "xxxxxxxxx",
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0",
}

ret = requests.get(url, headers=headers)
ret = ret.json()

to_push = []

for item in ret:
    content = item["text"]
    encoded = content.encode("utf-8")
    if len(encoded) > MAXSIZE:
        print("Too large, splitting")
        content_list = cut_content(encoded)
        template = item.copy()
        for i, content in enumerate(content_list):
            t = template.copy()
            t["text"] = content
            t["objectID"] = f'{t["objectID"]}_{i}'
            to_push.append(t)
    else:
        to_push.append(item)

```

如果我改了`objectID`上传会导致mx-space出错：

```
 ERROR   [Catch]  Cast to ObjectId failed for value "xxxxxxxxx-1" (type string) at path "_id" for model "posts"

  at SchemaObjectId.cast (/app/entrypoints.js:1073:883)
  at SchemaType.applySetters (/app/entrypoints.js:1187:226)
  at SchemaType.castForQuery (/app/entrypoints.js:1199:338)
  at cast (/app/entrypoints.js:159:5360)
  at Query.cast (/app/entrypoints.js:799:583)
  at Query._castConditions (/app/entrypoints.js:765:9879)
  at pn.Query._findOne (/app/entrypoints.js:768:4304)
  at pn.Query.exec (/app/entrypoints.js:784:5145)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async Promise.all (index 0) 
```

因此可能需要这边相关代码支持此功能。

### Alternative

使用其他键，比如'id'作为结果。

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by YKMdB3p** [comment]
实际上代码中是有对超过10KB的索引进行截断的，但是截断逻辑存在问题实际超过了大小。修改一下search.service.ts的代码或者直接丢掉text字段都能解决问题。我并不使用text字段作为搜索条件也不建议。

**Comment by Do1e** [comment]
> 实际上代码中是有对超过10KB的索引进行截断的，但是截断逻辑存在问题实际超过了大小。修改一下search.service.ts的代码或者直接丢掉text字段都能解决问题。我并不使用text字段作为搜索条件也不建议。

看了下代码里设定的截断大小为100K，实际免费额度目前是10K。  
建议改为环境变量。

我自己把分页搜索实现了一下，仅作参考：

```typescript
async buildAlgoliaIndexData() {

  ...

  function canBeDecoded(textEncoded: Uint8Array): boolean {
    try {
      new TextDecoder('utf-8', { fatal: true }).decode(textEncoded);
      return true
    } catch (e) {
      return false;
    }
  }

  const combineDocumentsSplited: any[] = []
  combineDocuments.flat().forEach((item) => {
    const objectToAdjust = JSON.parse(JSON.stringify(item))
    objectToAdjust.text = objectToAdjust.text.replace(/<style[^>]*>[\s\S]*?<\/style>/gi, '')
    objectToAdjust.text = objectToAdjust.text.replace(/<script[^>]*>[\s\S]*?<\/script>/gi, '')
    const encodedSize = new TextEncoder().encode(JSON.stringify(objectToAdjust)).length;
    if (encodedSize <= MAX_SIZE_IN_BYTES) {
      objectToAdjust.objectID = `${objectToAdjust.objectID}_0`;
      combineDocumentsSplited.push(objectToAdjust);
    } else {
      const textEncoded = new TextEncoder().encode(objectToAdjust.text);
      const textSize = textEncoded.length;
      const n = Math.ceil(textSize / (MAX_SIZE_IN_BYTES - encodedSize + textSize));
      var start = 0;
      for (let i = 0; i < n; i++) {
        const newObject = JSON.parse(JSON.stringify(objectToAdjust));
        var end = start + Math.floor(textSize / n);
        while (!canBeDecoded(textEncoded.slice(start, end))) {
          end--;
        }
        newObject.text = new TextDecoder('utf-8').decode(textEncoded.slice(start, end));
        newObject.objectID = `${newObject.objectID}_${i}`;
        combineDocumentsSplited.push(newObject);
        start = end;
      }
    }
  });
  return combineDocumentsSplited;
}
```
